### PR TITLE
Remove Carrenza VPN

### PR DESCRIPTION
**Pull request by richardTowers**
We still have one side of these VPN tunnels running in AWS (staging and production), but we no longer have any infrastructure running in Carrenza, so the tunnels can't be doing anyone any good.

Occasionally AWS email me about these tunnels having issues, and I think to myself "why do we still have VPN tunnels in Carrenza?". That is thinking time I could be spending on other, more relevant or interesting things, so let's remove the tunnels.

Roll out plan:

- I'll do a `terraform plan -destroy` for staging and production
- I'll get this reviewed along with the plan
- I'll also get a review for https://github.com/alphagov/govuk-aws-data/pull/1146 for the config behind this project
- Once approved, I'll destroy this project in staging and then production, and then merge the PRs

### CODE REVIEW

**Comment by richardTowers** [comment]
So, the applications situation with this terraform is different in all of the environments:

| Environment | Situation |
|------|------|
| Integration | No statefile for this project, no VPN resources in AWS |
| Staging | No statefile for this project, but there are VPN resources in the account, which appear to be left over from the infra-vpc project which used to own them |
| Production |  Statefile and resources exist, plan-destroy says 0 to add, 0 to change, 4 to destroy (which sounds sensible) |

Full production plan-destroy on Jenkins - https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5361/console

**Review by sengi — APPROVED** [review]
🚀

**Comment by richardTowers** [comment]
Terraform destroy ran successfully in production, going to have a look at staging to see if it can be cleaned up.

**Comment by richardTowers** [comment]
Staging cleaned up manually (I created a temporary terraform project based on an old version of infra-vpc, imported the resources, and then destroyed them). infra-vpc is applying cleanly from main now - https://deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/5365/console

VPN gone from all environments! 🚀

**Pull request merged**
