### PR TITLE
Per-app healthchecks on `backend` internal LB.

### PR DESCRIPTION
**Pull request by sengi**
### What

* Define a new ALB `govuk-backend-internal` for internal traffic.
* Use a single target group per app. Where an app is supposed to be reachable both internally and externally, point both LBs at the app's target group rather than creating duplicate target groups, which we can't afford because of the 50 TG per ASG hard limit.
* Move the existing `govuk-backend-public` ALB definition into the `app-backend` project. The two ALBs need to be in the same place in order to use the same set of TGs without excessive complexity.
* Move the service DNS records along with the ALBs. These belong together because they're inherently tightly coupled to the ALBs.
* Prevent ingress from the Internet to internal-only services via the public/external load balancer.

### Why

Our `lb_listener_rules` module has become unsuitable for configuring the `backend` load balancers. This is because:

* We need to do [per-app healthchecks](https://github.com/alphagov/govuk-aws/blob/master/doc/architecture/decisions/0037-alb-health-checks.md) in order for our services to be sufficiently reliable.
* The `backend` autoscaling group hosts 31 services and needs both an external and an internal LB. Most, but not all, of the services are available both internally and externally.
* In order to do per-app healthchecks on the internal LB, we need to upgrade it from classic ELB to ALB (like the external one).
* AWS has a hard limit of 50 target groups on a given autoscaling group. This isn't one of the quotas that they can raise for us.
* We only need a single TG for each application service (in order to healthcheck each app independently), but `lb_listener_rules` prevents us from doing this because it encapsulates the creation of the listener rule, TG and ASG attachment. With `lb_listener_rules`, we end up trying to attach 62 or more TGs to a single ASG and failing.

Therefore, given that we need per-app healthchecks before migrating the publisher apps to AWS, we have to move away from `lb_listener_rules`.

The lb_listener_rules module also makes extensive use of Terraform lists and `count`, which causes severe problems when there are many services on the same load balancer. These include the inability to remove a service without causing downtime for other services. We have encountered situations in which removing a service from near the top of the list results in Terraform failing part-way through the rollout, breaking the live configuration and entering a state which cannot be recovered from by re-running `apply`.

### Design goals / nonfunctional requirements

* Ease of understanding (relative to what we had before).
* Ease of maintenance.
* Flexibility.
    * We need to be able to easily adapt config to meet unforeseen future needs, not just anticipated ones.
* Straightforward changes like adding/removing a service or changing settings for a particular service should be simple and obvious to make and safe to roll out.
* Changes to one service should not be able to affect other services.
* Keeping related (or closely coupled or interdependent) config together.
    * If two config items need to be read together in order to understand what's going on, they should be in the same place unless there's an overriding reason for them not to be (for example if one of the config items is shared between many other TF projects and therefore warrants being in a central place or its own project).
    * We want to avoid making the user jump between lots of different files and having to keep an unnecessarily large amount of state in their head when making changes.
* Avoiding multiple definitions of information which would cause problems if they were to go out of sync.

#### Non-goals

 * Minimising the number of lines of code.
 * Avoiding repetition just for the sake of avoiding repetition.
    * It's important to remember that this is configuration code, not application logic. Good config code contains almost no logic.
    * This isn't supposed to be a program which generates config. It's supposed to *be* the config.

### Tips for reviewing

This is probably not one to review line-by-line 😅 I'd recommend going commit-by-commit, focusing on the _Avoid using lb_listener_rules module for backend LBs_ commit and assessing the overall approach and structure against the design goals above. The `terraform plan` output is as important as the code changes, of course (see links in comments below).

I'm not too worried about detail mistakes getting missed in review, because we're likely to catch those in testing. My primary concern is that we converge on a structure and approach that's maintainable for the future as well as solving the immediate practical problem.

### Requisite PRs in other repos

* alphagov/govuk-aws-data/pull/703

### CODE REVIEW

**Comment by sengi** [comment]
Terraform plans:

* [`app-backend` in Staging](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4133/console)
* [`infra-public-services` in Staging](https://ci-deploy.integration.publishing.service.gov.uk/job/Deploy_Terraform_GOVUK_AWS/4134/console)

**Comment by sengi** [comment]
Here's my audit of which services are behind the existing internal vs external LBs and comparing Integration against Production: https://docs.google.com/spreadsheets/d/1QqTS3Y4xw8FMoLn4_2jBPqXuhbQWeY1Jq48TTVp-sdo/edit

**Comment by rtrinque** [comment]
Love the design goals!

**Comment by issyl0** [comment]
Sorry but you're going to need to rebase this on master after I changed CI. :innocent:

**Comment by fredericfran-gds** [comment]
superseded by https://github.com/alphagov/govuk-aws/pull/1287

**Pull request closed without merging**
