### PR TITLE
Add an AWS credentials helper to govukcli

### PR DESCRIPTION
**Pull request by boffbowsh**
Handles fetching AWS sessions for both gds-users and the requested
GOV.UK environment, including requesting the MFA token.

We fetch and cache a session token for gds-users first so we can assume
roles in other accounts without having to re-request an MFA token.

Requires a small documentation change in the dev docs: https://github.com/alphagov/govuk-developer-docs/pull/746

```
$ govukcli aws s3 ls
Enter MFA Token:
```

### CODE REVIEW

**Comment by surminus** [comment]
I found an error:

```➜  ~/govuk/govuk-aws git:(add-aws-helper) ✗ govukcli aws
/usr/local/bin/govukcli: line 249: [: ==: unary operator expected
Enter MFA token: ^C```

**Comment by boffbowsh** [comment]
Ta, fixed

**Comment by surminus** [comment]
I successfully tested this 👍 

I think it would be good to update `govukcli.completion` along with this change to keep it up to date.

My other comment would be I think we should encourage people _not_ to store their credentials on disk - I personally really dislike this, although the MFA token goes some way in ensuring this isn't abused. I have an alternative method which maybe I'll expand on when this is merged.

**Comment by boffbowsh** [comment]
I've updated the bash completion for this

**Pull request merged**
