### PR TITLE
Remove UK Cloud VPN

### PR DESCRIPTION
**Pull request by richardTowers**
This is no longer required because we've worked with Civica to allowlist the IPs of our AWS NAT Gateways for the vast majority of their local authority customers.

Additionally, UK Cloud is in liquidation and is being shut down. The liquidators only expect the platform to be operational until 10 February 2023, and in the meantime the liquidators have been increasing prices exponentially to cover the costs of operating the platform with an ever diminished customer base.

I have notified UK Cloud and the liquidators that from the end of December 2022 we no longer require our account.

See also https://github.com/alphagov/govuk-aws-data/pull/1144

### CODE REVIEW

**Comment by richardTowers** [comment]
The destroy plan in staging:

```
$ terraform plan -destroy -var-file=staging.tfvars                                                                                                                                                                  
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.infra_networking: Refreshing state...
data.terraform_remote_state.infra_vpc: Refreshing state...
aws_customer_gateway.ukcloud_vpn_gateway: Refreshing state... (ID: cgw-0003cbc76f58f5fa2)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-004e90edd1b3bb512)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-05896e3b8657f76c2)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0757f8ce9a8f0de09)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0f89f08e09272cfe7)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0fb98c3bd38298229)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-07e15602056ca4bfa)
aws_vpn_connection.aws_ukcloud_vpn: Refreshing state... (ID: vpn-00bd506788f9e7899)
aws_vpn_connection_route.civica_cidr: Refreshing state... (ID: 213.143.135.0/24:vpn-00bd506788f9e7899)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_customer_gateway.ukcloud_vpn_gateway

  - aws_vpn_connection.aws_ukcloud_vpn

  - aws_vpn_connection_route.civica_cidr

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]


Plan: 0 to add, 0 to change, 9 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**Comment by richardTowers** [comment]
I'll destroy this in staging and production once the PR is approved (before merging).

**Review by ChrisBAshton — APPROVED** [review]

**Comment by richardTowers** [comment]
Staging destroy ✅ 

```
$ terraform destroy -var-file=staging.tfvars 
data.terraform_remote_state.infra_vpc: Refreshing state...
data.terraform_remote_state.infra_networking: Refreshing state...
aws_customer_gateway.ukcloud_vpn_gateway: Refreshing state... (ID: cgw-0003cbc76f58f5fa2)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-004e90edd1b3bb512)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0757f8ce9a8f0de09)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0fb98c3bd38298229)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-0f89f08e09272cfe7)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Refreshing state... (ID: vgw-07a35b30965dccb58_rtb-07e15602056ca4bfa)
aws_vpn_connection.aws_ukcloud_vpn: Refreshing state... (ID: vpn-00bd506788f9e7899)
aws_vpn_connection_route.civica_cidr: Refreshing state... (ID: 213.143.135.0/24:vpn-00bd506788f9e7899)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_customer_gateway.ukcloud_vpn_gateway

  - aws_vpn_connection.aws_ukcloud_vpn

  - aws_vpn_connection_route.civica_cidr

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]


Plan: 0 to add, 0 to change, 9 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-0fb98c3bd38298229)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-05896e3b8657f76c2)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-0f89f08e09272cfe7)
aws_vpn_connection_route.civica_cidr: Destroying... (ID: 213.143.135.0/24:vpn-00bd506788f9e7899)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-07e15602056ca4bfa)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-004e90edd1b3bb512)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Destroying... (ID: vgw-07a35b30965dccb58_rtb-0757f8ce9a8f0de09)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Destruction complete after 0s
aws_vpn_connection_route.civica_cidr: Destruction complete after 0s
aws_vpn_connection.aws_ukcloud_vpn: Destroying... (ID: vpn-00bd506788f9e7899)
aws_vpn_connection.aws_ukcloud_vpn: Still destroying... (ID: vpn-00bd506788f9e7899, 10s elapsed)
aws_vpn_connection.aws_ukcloud_vpn: Destruction complete after 11s
aws_customer_gateway.ukcloud_vpn_gateway: Destroying... (ID: cgw-0003cbc76f58f5fa2)
aws_customer_gateway.ukcloud_vpn_gateway: Destruction complete after 1s

Destroy complete! Resources: 9 destroyed.
```

**Comment by richardTowers** [comment]
Production destroy ✅ 

```
$ terraform destroy -var-file=production.tfvars 
data.terraform_remote_state.infra_networking: Refreshing state...
data.terraform_remote_state.infra_vpc: Refreshing state...
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Refreshing state... (ID: vgw-030bbd5f7fff53bf8_rtb-0d3bbd7066ec8cbbc)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Refreshing state... (ID: vgw-030bbd5f7fff53bf8_rtb-0c443ad6946387208)
aws_customer_gateway.ukcloud_vpn_gateway: Refreshing state... (ID: cgw-0249f68d13cf45f5a)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Refreshing state... (ID: vgw-030bbd5f7fff53bf8_rtb-0f44b7c0c50433690)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Refreshing state... (ID: vgw-030bbd5f7fff53bf8_rtb-0f43f57bf4a287a1b)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Refreshing state... (ID: vgw-030bbd5f7fff53bf8_rtb-0d1c2e094c21e285e)
aws_vpn_connection.aws_ukcloud_vpn: Refreshing state... (ID: vpn-00272a60828828cdb)
aws_vpn_connection_route.civica_cidr: Refreshing state... (ID: 213.143.135.0/24:vpn-00272a60828828cdb)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_customer_gateway.ukcloud_vpn_gateway

  - aws_vpn_connection.aws_ukcloud_vpn

  - aws_vpn_connection_route.civica_cidr

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]

  - aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]


Plan: 0 to add, 0 to change, 9 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0939872e7068ded2c)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0d3bbd7066ec8cbbc)
aws_vpn_connection_route.civica_cidr: Destroying... (ID: 213.143.135.0/24:vpn-00272a60828828cdb)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0f43f57bf4a287a1b)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0d1c2e094c21e285e)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0c443ad6946387208)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Destroying... (ID: vgw-030bbd5f7fff53bf8_rtb-0f44b7c0c50433690)
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[0]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[1]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[1]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[2]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation_reserved_ips[0]: Destruction complete after 0s
aws_vpn_gateway_route_propagation.ukcloud_route_propagation[2]: Destruction complete after 0s
aws_vpn_connection_route.civica_cidr: Destruction complete after 1s
aws_vpn_connection.aws_ukcloud_vpn: Destroying... (ID: vpn-00272a60828828cdb)
aws_vpn_connection.aws_ukcloud_vpn: Still destroying... (ID: vpn-00272a60828828cdb, 10s elapsed)
aws_vpn_connection.aws_ukcloud_vpn: Destruction complete after 11s
aws_customer_gateway.ukcloud_vpn_gateway: Destroying... (ID: cgw-0249f68d13cf45f5a)
aws_customer_gateway.ukcloud_vpn_gateway: Destruction complete after 0s

Destroy complete! Resources: 9 destroyed.
```

**Pull request merged**
