### PR TITLE
Add an RDS replica to Transition PostgreSQL database

### PR DESCRIPTION
**Pull request by issyl0**
- Bouncer uses the database secondary (here, standby) to read its data, so we set one up.

### CODE REVIEW

**Comment by issyl0** [comment]
This seems to `plan` correctly.

**Comment by surminus** [comment]
This seems to create a full new RDS instance rather than a secondary. See [here](https://github.com/alphagov/govuk-aws/blob/master/terraform/projects/app-postgresql/main.tf#L74-L83) for setting up a standby.

**Comment by issyl0** [comment]
I did the thing in the link first, following your PR to add replicas to `app-postgresql`, and then wondered why there were so many more options and thought I'd done it wrong so started again. I'll do it again again. 😪

**Comment by issyl0** [comment]
@surminus I just re-did this. :-)

**Pull request merged**
