### PR TITLE
Remove three data science apps

### PR DESCRIPTION
**Pull request by nacnudus**
This removes three apps that were maintained by the former Data Labs
team, which has been moved out of GOV.UK into another directorate.

- Knowledge Graph. This has been reimplemented in GCP.
- Data Science App. This hasn't been used for a long time, and GOV.UK no
  longer has any data scientists to use it.  It refers to some parts of
  the Knowledge Graph, so it is easier to delete it now than to
  disentangle it.
- Accessibility Reports. This is used one a year, at most. It is
  uncertain whether it will be used again. It depends entirely on a
  data file that the Knowledge Graph creates. If required, the Data
  Products team in the Product and Technology directorate will recreate
  it, using the new implementation of the GovGraph in GCP.

See related changes in https://github.com/alphagov/govuk-aws-data.

### CODE REVIEW

**Comment by nacnudus** [comment]
The three apps to delete are:

- app-accessibility-reports
- app-data-science
- app-data-science-data

This can be done with the command `terraform destroy`, via the GDS CLI, _before_
the terraform config files of those apps are deleted.

## app-data-science

Unfortunately, we can't destroy this one ourselves.

The backend of app-data-science is in the "tools" environment, as defined in `terraform/projects/app-data-science/tools.govuk.backend`.  The `govuk-integration-admin` role doesn't have permissions there.

```
$ gds aws govuk-integration-admin -- tools/build-terraform-project.sh -c destroy -p app-data-science -d ../govuk-aws-data/data -e tools -s govuk
```

```
Access denied
```

## app-data-science-data

```
$ gds aws govuk-integration-admin -- tools/build-terraform-project.sh -c destroy -p app-data-science-data -d ../govuk-aws-data/data -e integration -s govuk
```

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_autoscaling_group.data-science-data-dev_asg

  - aws_autoscaling_group.data-science-data_asg

  - aws_autoscaling_schedule.data-science-data_schedule-spin-down

  - aws_autoscaling_schedule.data-science-data_schedule-spin-up

  - aws_iam_instance_profile.data-science-data_instance_profile

  - aws_iam_policy.data-science-data_read_secrets_from_secrets_manager_policy

  - aws_iam_policy.data-science-data_read_ssm_policy

  - aws_iam_policy.invoke_sagemaker_govner_endpoint_policy

  - aws_iam_role.data-science-data_role

  - aws_iam_role_policy_attachment.data-science-data_read_content_store_backups_bucket_role_attachment

  - aws_iam_role_policy_attachment.data-science-data_read_related_links_bucket_role_attachment

  - aws_iam_role_policy_attachment.data-science-data_read_secrets_from_secrets_manager_role_attachment

  - aws_iam_role_policy_attachment.data-science-data_read_ssm_role_attachment

  - aws_iam_role_policy_attachment.invoke_sagemaker_govner_endpoint_role_attachment

  - aws_iam_role_policy_attachment.read_write_data_infrastructure_bucket_role_attachment

  - aws_launch_template.data-science-data-dev_launch_template

  - aws_launch_template.data-science-data_launch_template

  - aws_security_group_rule.publishing-api-rds_ingress_data-science-data_postgres
```

## app-knowledge-graph

```
$ gds aws govuk-integration-admin -- tools/build-terraform-project.sh -c destroy -p app-knowledge-graph -d ../govuk-aws-data/data -e integration -s govuk

var.elb_external_certname
  The ACM cert domain name to find the ARN of

  Enter a value: integration.govuk.digital

var.external_domain_name
  The domain name of the external DNS records, it could be different from the zone name

  Enter a value: integration.govuk.digital

var.external_zone_name
  The name of the Route53 zone that contains external records

  Enter a value: integration.govuk.digital
```

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_autoscaling_group.knowledge-graph-dev_asg

  - aws_autoscaling_group.knowledge-graph_asg

  - aws_autoscaling_schedule.knowledge-graph_schedule-spin-down

  - aws_autoscaling_schedule.knowledge-graph_schedule-spin-up

  - aws_elb.knowledge-graph-dev_elb_external

  - aws_elb.knowledge-graph_elb_external

  - aws_iam_instance_profile.knowledge-graph_instance_profile

  - aws_iam_policy.knowledge-graph_read_ssm_policy

  - aws_iam_policy.knowledge-graph_register_instance_with_elb_policy

  - aws_iam_policy.read_write_data_infrastructure_bucket_policy

  - aws_iam_role.knowledge-graph_role

  - aws_iam_role_policy_attachment.knowledge-graph_read_content_store_backups_bucket_role_attachment

  - aws_iam_role_policy_attachment.knowledge-graph_read_related_links_bucket_role_attachment

  - aws_iam_role_policy_attachment.knowledge-graph_read_ssm_role_attachment

  - aws_iam_role_policy_attachment.knowledge-graph_register_instance_with_elb_role_attachment

  - aws_iam_role_policy_attachment.read_write_data_infrastructure_bucket_role_attachment

  - aws_launch_template.knowledge-graph-dev_launch_template

  - aws_launch_template.knowledge-graph_launch_template

  - aws_route53_record.knowledge_graph_dev_service_record_external

  - aws_route53_record.knowledge_graph_service_record_external

  - aws_s3_bucket.data_infrastructure_bucket
```

**Review by richardTowers — APPROVED** [review]
Amazing work recreating these, and thank you for doing the cleanup.

I can help you destroy the stuff in the tools account I think - I'll have a look at this now.

Good spot finding the bits in infra-security-groups that need to change, I guess there are no other deployments that depend on things in this one?

**Comment by richardTowers** [comment]
Plan for destroying `app-data-science`:

```
[cloudshell-user@ip-10-0-127-227 app-data-science]$ terraform plan --destroy -var aws_environment=tools -var esm_trusty_token=null -var office_ips=[] -var remote_state_bucket=govuk-terraform-steppingstone-tools -var stackname=tools -var 'user_data_snippets=["90-data-science-base"]' -var 'instance_ami_filter_name="*"'
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.infra_networking: Refreshing state...
data.terraform_remote_state.infra_monitoring: Refreshing state...
null_resource.node_autoscaling_group_tags[0]: Refreshing state... (ID: 604568512914361170)
null_resource.node_autoscaling_group_tags[0]: Refreshing state... (ID: 7741159926109629514)
null_resource.node_autoscaling_group_tags[1]: Refreshing state... (ID: 4833792930944922953)
null_resource.node_autoscaling_group_tags[2]: Refreshing state... (ID: 8453419934129608642)
null_resource.node_autoscaling_group_tags[1]: Refreshing state... (ID: 5520629032840860218)
null_resource.node_autoscaling_group_tags[2]: Refreshing state... (ID: 4547637514992336399)
null_resource.user_data: Refreshing state... (ID: 7338380117573598749)
data.terraform_remote_state.infra_vpc: Refreshing state...
data.terraform_remote_state.infra_root_dns_zones: Refreshing state...
data.terraform_remote_state.infra_stack_dns_zones: Refreshing state...
data.terraform_remote_state.infra_security_groups: Refreshing state...
aws_iam_role.node_iam_role: Refreshing state... (ID: data-science-1)
aws_security_group.data-science: Refreshing state... (ID: sg-03bc73750c68caf45)
aws_iam_role.node_iam_role: Refreshing state... (ID: data-science-2)
aws_iam_policy.node_iam_policy_default: Refreshing state... (ID: arn:aws:iam::900804735337:policy/data-science-1-default)
aws_iam_policy.node_iam_policy_default: Refreshing state... (ID: arn:aws:iam::900804735337:policy/data-science-2-default)
data.aws_ami.node_ami_ubuntu: Refreshing state...
data.aws_ami.node_ami_ubuntu: Refreshing state...
aws_elb.data-science_external_elb: Refreshing state... (ID: govuk-data-science)
aws_security_group_rule.data-science_ingress_offsite-ssh_ssh: Refreshing state... (ID: sgrule-2434077335)
aws_security_group_rule.data-science_egress_any_any: Refreshing state... (ID: sgrule-4133137856)
aws_iam_instance_profile.node_instance_profile: Refreshing state... (ID: data-science-2)
aws_iam_instance_profile.node_instance_profile: Refreshing state... (ID: data-science-1)
aws_cloudwatch_metric_alarm.elb_surgequeuelength: Refreshing state... (ID: govuk-data-science-external-elb-surgequeuelength)
aws_cloudwatch_metric_alarm.elb_healthyhostcount: Refreshing state... (ID: govuk-data-science-external-elb-healthyhostcount)
aws_iam_role_policy_attachment.node_iam_role_policy_attachment_default: Refreshing state... (ID: data-science-1-20190214142024772700000001)
aws_iam_role_policy_attachment.node_iam_role_policy_attachment_default: Refreshing state... (ID: data-science-2-20190214141627378300000001)
aws_launch_configuration.node_launch_configuration: Refreshing state... (ID: data-science-2-20190220124512428200000001)
aws_launch_configuration.node_launch_configuration: Refreshing state... (ID: data-science-1-20190214142025427300000002)
aws_autoscaling_group.node_autoscaling_group: Refreshing state... (ID: data-science-2)
aws_autoscaling_group.node_autoscaling_group: Refreshing state... (ID: data-science-1)
aws_autoscaling_attachment.node_autoscaling_group_attachment_classic: Refreshing state... (ID: data-science-1-20190214142042621300000003)
aws_autoscaling_notification.node_autoscaling_group_notifications: Refreshing state... (ID: arn:aws:sns:eu-west-2:900804735337:tools-notifications)
aws_autoscaling_notification.node_autoscaling_group_notifications: Refreshing state... (ID: arn:aws:sns:eu-west-2:900804735337:tools-notifications)
aws_autoscaling_attachment.node_autoscaling_group_attachment_classic: Refreshing state... (ID: data-science-2-20190214141645579300000003)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  - aws_elb.data-science_external_elb

  - aws_security_group.data-science

  - aws_security_group_rule.data-science_egress_any_any

  - aws_security_group_rule.data-science_ingress_offsite-ssh_ssh

  - null_resource.user_data

  - module.alarms-elb-data-science-internal.aws_cloudwatch_metric_alarm.elb_healthyhostcount

  - module.alarms-elb-data-science-internal.aws_cloudwatch_metric_alarm.elb_surgequeuelength

  - module.data-science-1.aws_autoscaling_attachment.node_autoscaling_group_attachment_classic

  - module.data-science-1.aws_autoscaling_group.node_autoscaling_group

  - module.data-science-1.aws_autoscaling_notification.node_autoscaling_group_notifications

  - module.data-science-1.aws_iam_instance_profile.node_instance_profile

  - module.data-science-1.aws_iam_policy.node_iam_policy_default

  - module.data-science-1.aws_iam_role.node_iam_role

  - module.data-science-1.aws_iam_role_policy_attachment.node_iam_role_policy_attachment_default

  - module.data-science-1.aws_launch_configuration.node_launch_configuration

  - module.data-science-1.null_resource.node_autoscaling_group_tags[0]

  - module.data-science-1.null_resource.node_autoscaling_group_tags[1]

  - module.data-science-1.null_resource.node_autoscaling_group_tags[2]

  - module.data-science-2.aws_autoscaling_attachment.node_autoscaling_group_attachment_classic

  - module.data-science-2.aws_autoscaling_group.node_autoscaling_group

  - module.data-science-2.aws_autoscaling_notification.node_autoscaling_group_notifications

  - module.data-science-2.aws_iam_instance_profile.node_instance_profile

  - module.data-science-2.aws_iam_policy.node_iam_policy_default

  - module.data-science-2.aws_iam_role.node_iam_role

  - module.data-science-2.aws_iam_role_policy_attachment.node_iam_role_policy_attachment_default

  - module.data-science-2.aws_launch_configuration.node_launch_configuration

  - module.data-science-2.null_resource.node_autoscaling_group_tags[0]

  - module.data-science-2.null_resource.node_autoscaling_group_tags[1]

  - module.data-science-2.null_resource.node_autoscaling_group_tags[2]


Plan: 0 to add, 0 to change, 29 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

(Note doing this in an AWS cloudshell without access to govuk-aws-data, so I've made up some placeholder values for the `-var`s - they mostly don't matter for a destroy.

**Comment by nacnudus** [comment]
Thanks @richardTowers!

A note to follow up after the weekend.  We backed up the bucket, ran both the commands that we can, and got these errors for `app-govuk-knowledge-graph`.

```
Error: Error applying plan:

3 errors occurred:
	* aws_iam_policy.knowledge-graph_read_ssm_policy (destroy): 1 error occurred:
	* aws_iam_policy.knowledge-graph_read_ssm_policy: Error deleting IAM policy arn:aws:iam::210287912431:policy/knowledge-graph_read_ssm_policy: &awserr.requestError{awsError:(*awserr.baseError)(0xc000a6a100), statusCode:409, requestID:"c6666e8a-7ff4-4a26-a077-b3c2bb1e57d2"}


	* aws_iam_policy.read_write_data_infrastructure_bucket_policy (destroy): 1 error occurred:
	* aws_iam_policy.read_write_data_infrastructure_bucket_policy: Error deleting IAM policy arn:aws:iam::210287912431:policy/read_write_data_infrastructure_bucket_policy: &awserr.requestError{awsError:(*awserr.baseError)(0xc000a6a900), statusCode:409, requestID:"6c7bca50-761e-49cc-9940-94a7c7a0cb8e"}


	* aws_s3_bucket.data_infrastructure_bucket (destroy): 1 error occurred:
	* aws_s3_bucket.data_infrastructure_bucket: error deleting S3 Bucket (govuk-data-infrastructure-integration): BucketNotEmpty: The bucket you tried to delete is not empty. You must delete all versions in the bucket.
	status code: 409, request id: 3D533R3VZN797MD5, host id: bUwlhpkjA+00f4WTYsyjXoy1qKJy3I1ULx7aM5s9BA/z4Wj4H4mR0XlboG+OUAwrcQyaU0PJfcA=
```

**Comment by maxf** [comment]
I've done this a few times. I have scripts somewhere to empty all versions of a bucket. I'll dig them out

**Comment by nacnudus** [comment]
Hi @richardTowers, please could you run the `terraform destroy` for real?  https://github.com/alphagov/govuk-aws/pull/1650#issuecomment-1318531303.  Thanks.

**Review by ChrisBAshton — COMMENTED** [review]
Please also follow the steps to remove these apps from the Developer Docs etc, when they're retired. Thank you!

https://docs.publishing.service.gov.uk/manual/retiring-an-application.html

**Comment by maxf** [comment]
Done. All that remains is for @richardTowers to finish destroying

**Comment by richardTowers** [comment]
Finally got around to destroying this in the tools environment 😅 

All done!

**Pull request merged**
