### PR TITLE
First draft of the new lb removal plans

### PR DESCRIPTION
**Pull request by deanwilson**

### CODE REVIEW

**Comment by surminus** [comment]
A consequence to note will be moving the GOVUK-request-ID header thing, as this won't be possible to emulate on an ELB.

**Comment by boffbowsh** [comment]
This makes sense to me. We need to ensure that we move the generation of the request id header to within the applications though.

**Comment by surminus** [comment]
I'm already in the midst of removing frontend-lb, and the request ID header is set on the cache machines I think so no biggie here.

**Comment by boffbowsh** [comment]
👍

**Pull request merged**
