### PR TITLE
Enable Enhanced Monitoring on RDS Postgres.

### PR DESCRIPTION
**Pull request by sengi**
* Enable Enhanced Monitoring on all of our RDS Postgres instances.
* Keep the RDS Postgres standby instance at its current size.

We recently enabled Enhanced Monitoring on the shared Postgres RDS in production. This change reflects that, and also enables it on all the other Postgres RDS instances in all environments. The cost of doing so is negligible (just a modest amount of log storage) and the benefits are significant, as it gives us per-process history of CPU usage (and therefore per-query history of CPU usage, albeit sampled).

We also recently enlarged the shared Postgres RDS in production to 12xlarge. We want to avoid applying the same change to the standby instance, which appears to be disused. We'll want to confirm that it's disused and if so, decommission it in the near future - but I'll leave that for another PR.

The `rds-monitoring-role` IAM role and policy attachment were already added in #1276.

alphagov/govuk-aws-data#702 keeps the Integration standby instance the same size.

### CODE REVIEW

**Comment by sengi** [comment]
TF plans:

Staging `app-postgresql`:

```
Terraform will perform the following actions:

  ~ module.postgresql-primary_rds_instance.aws_db_instance.db_instance
      monitoring_interval: "0" => "60"


Plan: 0 to add, 1 to change, 0 to destroy.
```

No diff in Prod `app-postgresql`.

Staging `app-transition-postgresql`:

```
Terraform will perform the following actions:

  ~ module.transition-postgresql-primary_rds_instance.aws_db_instance.db_instance
      monitoring_interval: "0" => "60"
      monitoring_role_arn: "" => "arn:aws:iam::696911096973:role/rds-monitoring-role"

  ~ module.transition-postgresql-standby_rds_instance.aws_db_instance.db_instance_replica
      monitoring_interval: "0" => "60"
      monitoring_role_arn: "" => "arn:aws:iam::696911096973:role/rds-monitoring-role"


Plan: 0 to add, 2 to change, 0 to destroy.
```

Staging `app-content-data-api-postgresql`:

```
Terraform will perform the following actions:

  ~ module.content-data-api-postgresql-primary_rds_instance.aws_db_instance.db_instance
      monitoring_interval: "0" => "60"
      monitoring_role_arn: "" => "arn:aws:iam::696911096973:role/rds-monitoring-role"


Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by sengi** [comment]
TF plan for `app-postgresql` in Integration (it looks like an earlier change to enable slow query logging has yet to be applied there, perhaps?)

```
Terraform will perform the following actions:

  + aws_db_parameter_group.postgresql_pg
      id:                                <computed>
      arn:                               <computed>
      description:                       "Managed by Terraform"
      family:                            "postgres9.6"
      name:                              <computed>
      name_prefix:                       "postgresql-pg-"
      parameter.#:                       "2"
      parameter.3271061621.apply_method: "immediate"
      parameter.3271061621.name:         "log_min_duration_statement"
      parameter.3271061621.value:        "10000"
      parameter.418023221.apply_method:  "immediate"
      parameter.418023221.name:          "log_statement"
      parameter.418023221.value:         "all"

  ~ module.postgresql-primary_rds_instance.aws_db_instance.db_instance
      monitoring_interval:               "0" => "60"
      monitoring_role_arn:               "" => "arn:aws:iam::210287912431:role/rds-monitoring-role"
      parameter_group_name:              "default.postgres9.6" => "${var.parameter_group_name}"

  ~ module.postgresql-standby_rds_instance.aws_db_instance.db_instance_replica
      parameter_group_name:              "default.postgres9.6" => "${var.parameter_group_name}"


Plan: 1 to add, 2 to change, 0 to destroy.
```

**Comment by sengi** [comment]
Force-push just to squash the docs commits and a minor rewording of one of the commit messages.

**Comment by sengi** [comment]
I've also tested that the change to the `rds_instance` module results in no diff to existing clusters when the `monitoring_interval` parameter isn't set (not that we have any where it isn't set, any more).

**Comment by smford** [comment]
> TF plan for `app-postgresql` in Integration (it looks like an earlier change to enable slow query logging has yet to be applied there, perhaps?)
> 
> ```
>       ...
>       parameter.3271061621.apply_method: "immediate"
>       parameter.3271061621.name:         "log_min_duration_statement"
>       parameter.3271061621.value:        "10000"
>       parameter.418023221.apply_method:  "immediate"
>       parameter.418023221.name:          "log_statement"
>       parameter.418023221.value:         "all"
>       ...
> ```

Yup that is correct!

**Pull request merged**
