### PR TITLE
Make out-of-date docs fail CI

### PR DESCRIPTION
**Pull request by issyl0**
- We often forget to run this script when we update files, so instead
  I'm adding it as a CI step that fails when
  changes are detected by the `terraform-docs` command.

### CODE REVIEW

**Comment by issyl0** [comment]
Oh good, it works already:

```
+ find . -name *.tf
+ xargs tools/check-for-docs.sh
Must install terraform-docs
```

😂

**Comment by tijmenb** [comment]
Oh yes! I ran into that too in https://github.com/alphagov/govuk-aws/compare/docs-fail-ci?expand=1 and gave up :(

**Comment by issyl0** [comment]
The `terraform-docs` package is now installed (💦) but I'm seeing some weird stuff with the output of the script - it wants to *remove* things from READMEs. I'm not sure that's right. It was also looking at all `.tf` files, not just `main.tf` like the old script, so I edited it to only `main.tf` files, but I'm still not convinced it's working. Tempted just to use @tijmenb's branch instead!

**Comment by issyl0** [comment]
I stole @tijmenb's code for this, but a rebase and removed all notion that I'd ever `cherry-pick`ed the commit - sorry Tijmen!

This is ready to go.

**Pull request merged**
